### ISSUE TITLE
Pip install failing from master

### ISSUE THREAD

**Issue by aribornstein** [NervanaSystems/nlp-architect#26] opened 2019-01-07 09:12 UTC
#### Target objective:
pip Install .

#### Steps to objective:
Successfully built nlp-architect
spacy 2.0.18 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
Installing collected packages: spacy, nlp-architect
Killed

**Comment by AlonEirew** [comment] 2019-01-07 09:32
@peteriz just a reminder, it might be related to the issue we saw SpaCy had in version 2.0.19, which we fixed by adding a constraint in setup.py [spacy < 2.0.19] in order to fix..

**Comment by peteriz** [comment] 2019-01-08 13:44
Hi @aribornstein, do you have any additional output related to the error?

**Comment by anujstam** [comment] 2019-03-15 12:52
I have a similar installation problem as well, with a direct pip install from master failing, but the incompatibilities are different. The error indicates that fasttextmirror failed to build, and a conflict between spacy and regex versions
---Error Text---
Failed to build fasttextmirror
spacy 2.0.11 has requirement regex==2017.4.5, but you'll have regex 2018.2.21 which is incompatible.

I'm installing directly via pip install nlp_architect

**Comment by amit8121** [comment] 2019-03-27 16:42
I have a similar installation issue with both direct pip install and building from source code. It's the same issue with both techniques: 

**I'm on - > Windows 10 OS
Python: 3.6.8
Inside a Anaconda Virtual Environment.**

Issue: 
` error: command 'D:\\Visual Studio Community 2017\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for fasttextmirror
  Running setup.py clean for fasttextmirror
Failed to build fasttextmirror
spacy 2.0.11 has requirement regex==2017.4.5, but you'll have regex 2018.2.21 which is incompatible.`
 
.......

`error: command 'D:\\Visual Studio Community 2017\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "D:\Anaconda3\envs\Test\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\amith\\AppData\\Local\\Temp\\pip-install-fffscuuu\\fasttextmirror\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\amith\AppData\Local\Temp\pip-record-wwopskn_\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\amith\AppData\Local\Temp\pip-install-fffscuuu\fasttextmirror\`


Initially my error was more with fasttextmirror build. The build used to fail and throw me an error that some C++ libraries were missing, after some googling I figured out that I need to install some Windows SDKs which comes with all necessary c++ libraries, but then I run in to this issue.

I understand that the issue is with some c++ libraries, but from whatever I've tried so far, I wasn't successful. 

P.S: I tried downgrading and upgrading all packages which were at fault, then I run in to C++ library issue and I still see the build for fasttextmirror failing. I was able to find original binary wheels for fasttext but not for fasttextmirror.

**Comment by peteriz** [comment] 2019-03-31 11:04
> I have a similar installation problem as well, with a direct pip install from master failing, but the incompatibilities are different. The error indicates that fasttextmirror failed to build, and a conflict between spacy and regex versions
> ---Error Text---
> Failed to build fasttextmirror
> spacy 2.0.11 has requirement regex==2017.4.5, but you'll have regex 2018.2.21 which is incompatible.
> 
> I'm installing directly via pip install nlp_architect

The spacy and regex conflict is not a big issue. However, fasttextmirror has compiler requirements that are needed for successful installation. Are you installing on Linux/Mac OS?
You can bypass the issue by manually installing fasttext from here (https://github.com/facebookresearch/fastText)

**Comment by peteriz** [comment] 2019-03-31 11:07
Hi @amit8121, we have not verified the installation of NLP Architect on Windows OS and we only support Linux/Mac OS; However, it might work on windows. Fasttext is a bit tricky to install on Windows, have you tried this?
https://github.com/facebookresearch/fastText/issues/548

**Comment by anujstam** [comment] 2019-04-05 06:34
I cloned the repository and replaced fasttextmirror with fasttext-win, which is supposed to be a version of fasttext for Windows and it installed without any errors. I have not run any extensive tests but it seems to be a possible workaround to the issue

**Comment by peteriz** [comment] 2019-04-05 08:20
@anujstam thanks for letting us know!

**Closed** 2019-08-21 13:52 UTC
